version: '3'

networks:
  backend:
    driver: bridge

volumes:
  postgres-database:
    driver: local

services:
    php:
        container_name: php
        image: php-symfony:${PHP_VERSION}
        build:
            context: ./docker/php
            args:
                APP_NAME: ${APP_NAME}
                PHP_VERSION: ${PHP_VERSION}
        ports: ['8000:8000']
        volumes:
            - ./:/usr/src
        tty: true
        environment:
            APP_NAME: ${APP_NAME}
            SYMFONY_VERSION: ${SYMFONY_VERSION}
        env_file:
            - ./${APP_NAME}/.env
        depends_on:
            - database
        networks:
            - backend
    database:
        container_name: database
        image: postgres:13
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: ['15432:5432']
        volumes:
            - postgres-database:/var/lib/postgresql/data
        networks:
            - backend